name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Viviss-18
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23ff4fa3&color_dots=%23161b27,%23311b2b,%2350223a,%23702b4c,%23ff69b4
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23ff4fa3&color_dots=%23161b27,%23311b2b,%2350223a,%23702b4c,%23ff69b4

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
